// Database of the 99 Names of Allah (Asma-ul-Husna)
// Each name is structured to fit the existing Dhikr schema, enabling seamless integration.

export const SEED_NAMES_OF_ALLAH = [
  {
    id: "name_1",
    tr: "Ar-Rahmaan",
    arabic: "الرَّحْمَنُ",
    en: "The Most Merciful",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah has ninety-nine names, and whoever preserves them will enter Paradise.' (Bukhari)",
    story: "Mentioned at the start of almost every Surah, this name represents Allah's expansive mercy that encompasses all creation.",
    benefits: "Reciting this name fills the heart with hope, softens hardness, and reminds us of Allah's unconditional grace."
  },
  {
    id: "name_2",
    tr: "Ar-Raheem",
    arabic: "الرَّحِيمُ",
    en: "The Especially Merciful",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah's Messenger ﷺ said: 'Allah divided Mercy into one hundred parts. He kept ninety-nine parts with Him and sent down one part to the earth.' (Muslim)",
    story: "While Ar-Rahman is His general mercy for all, Ar-Raheem is His specific, intimate mercy saved especially for the believers.",
    benefits: "Reminds us that Allah is intimately aware of our struggles and is always ready to forgive and show mercy to those who ask."
  },
  {
    id: "name_3",
    tr: "Al-Malik",
    arabic: "الْمَلِكُ",
    en: "The Absolute Ruler",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'On the Day of Resurrection, Allah will grasp the earth and fold the heavens... and say: I am the King! Where are the kings of the earth?' (Bukhari)",
    story: "He is the ultimate Sovereign whose dominion never decays, unlike the temporary, flawed kings and rulers of this world.",
    benefits: "Invoking Al-Malik helps release the fear of human authority and builds humility, recognizing that only Allah owns true sovereignty."
  },
  {
    id: "name_4",
    tr: "Al-Quddus",
    arabic: "الْقُدُّوسُ",
    en: "The Pure / Holy One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Messenger of Allah ﷺ used to say in his bowing and prostration: 'Subboohun Quddoos, Rabb-ul-mala'ikati war-rooh' (Glory and purity be to the Lord of the angels and the Spirit).",
    story: "He is absolutely free from any imperfection, error, deficiency, or human-like limitation.",
    benefits: "Helps purify the mind from negative thoughts and brings peace by focusing on the absolute perfection of the Creator."
  },
  {
    id: "name_5",
    tr: "As-Salam",
    arabic: "السَّلَامُ",
    en: "The Source of Peace",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "After ending prayers, the Prophet ﷺ would say: 'Allahumma antas-salam wa minkas-salam' (O Allah, You are Peace and from You is peace).",
    story: "He is the giver of tranquility, safety, and security. Peace in this world and the greeting of peace in the Hereafter come only from Him.",
    benefits: "Reciting this name calms severe anxiety, restores inner tranquility, and invites peace into troubled relationships."
  },
  {
    id: "name_6",
    tr: "Al-Mu'min",
    arabic: "الْمُؤْمِنُ",
    en: "The Inspirer of Faith / Giver of Security",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'I seek refuge in Your pleasure from Your anger, and in Your security from Your punishment.'",
    story: "He is the one who puts faith in the hearts of believers and guarantees safety to those who seek His refuge.",
    benefits: "Strengthens faith during times of doubt and brings comfort to those feeling threatened, insecure, or vulnerable."
  },
  {
    id: "name_7",
    tr: "Al-Muhaymin",
    arabic: "الْمُهَيْمِنُ",
    en: "The Guardian / Overseer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'He is Allah... Al-Muhaymin.' (Surah Al-Hashr 59:23)",
    story: "He is the supreme witness who watches over all actions, protects the weak, and preserves the order of the entire universe.",
    benefits: "Encourages self-accountability (*Muhasabah*) and brings a sense of being lovingly watched over and guarded by Allah."
  },
  {
    id: "name_8",
    tr: "Al-Aziz",
    arabic: "الْعَزِيزُ",
    en: "The All-Mighty / Invincible",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said in his supplication: 'I seek refuge in Your might (Izzah) — none has the right to be worshipped but You.' (Bukhari)",
    story: "He possesses absolute power and honor. No force can overcome Him, and He is the source of all dignity and strength.",
    benefits: "Invoked when feeling helpless, oppressed, or humiliated, seeking Allah's honor and invincible strength."
  },
  {
    id: "name_9",
    tr: "Al-Jabbar",
    arabic: "الْجَبَّارُ",
    en: "The Compeller / Restorer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to pray: 'O Allah, forgive me, have mercy on me, guide me, support me (ajburni), and provide for me.'",
    story: "Al-Jabbar is double-sided: He has the power to compel all creation to His will, yet He is also the Restorer who binds broken hearts.",
    benefits: "The perfect name to recite when heartbroken, defeated, or seeking repair for shattered hopes."
  },
  {
    id: "name_10",
    tr: "Al-Mutakabbir",
    arabic: "الْمُتَكَبِّرُ",
    en: "The Supreme / Majestic",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in a Hadith Qudsi: 'Pride is My cloak, and Majesty is My robe. Whoever disputes with Me for either, I will cast them into the Fire.' (Abu Dawud)",
    story: "He is the only one who truly deserves greatness. Any pride shown by human beings is a delusion, as true majesty belongs to Him alone.",
    benefits: "Reminds the reciter of their humility, breaking down arrogance and self-centeredness."
  },
  {
    id: "name_11",
    tr: "Al-Khaliq",
    arabic: "الْخَالِقُ",
    en: "The Creator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah was there and there was nothing other than Him, and His Throne was over the water.' (Bukhari)",
    story: "He brings things from non-existence into existence, planning their design and characteristics perfectly before they exist.",
    benefits: "Builds deep appreciation for nature and the miracle of existence, reminding us that we are created with absolute purpose."
  },
  {
    id: "name_12",
    tr: "Al-Bari",
    arabic: "الْبَارِئُ",
    en: "The Originator / Maker",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'He is Allah, the Creator, the Inventor (Al-Bari), the Fashioner.' (Surah Al-Hashr 59:24)",
    story: "He executes the creation process, bringing what He planned into physical reality with perfect proportion and no flaws.",
    benefits: "Invoked when seeking order in chaotic times, or when asking for healing, as He shapes and restores physical bodies."
  },
  {
    id: "name_13",
    tr: "Al-Musawwir",
    arabic: "الْمُصَوِّرُ",
    en: "The Fashioner / Shaper",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'When the fetus has passed forty-two nights, Allah sends an angel who shapes it (musawwiruha)...' (Muslim)",
    story: "He gives every creation its unique shape, color, features, and beauty, ensuring no two things in the universe are identical.",
    benefits: "Fosters self-acceptance and appreciation for one's appearance and uniqueness, countering comparison and insecurity."
  },
  {
    id: "name_14",
    tr: "Al-Ghaffar",
    arabic: "الْغَفَّارُ",
    en: "The Repeatedly Forgiving",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in a Hadith Qudsi: 'O son of Adam, if you come to Me with sins nearly as great as the earth and meet Me without partners, I will bring you forgiveness nearly as great as it.' (Tirmidhi)",
    story: "He is the one who repeatedly veils and forgives our sins, hiding our flaws in this world and wiping them away in the next.",
    benefits: "Offers immense relief to those carrying guilt. Recited to ask for forgiveness for recurring or deep-seated mistakes."
  },
  {
    id: "name_15",
    tr: "Al-Qahhar",
    arabic: "الْقَهَّارُ",
    en: "The Subduer / Overcomer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to pray at night: 'La ilaha illallahul Wahidul Qahhar' (There is no god but Allah, the One, the Subduer).",
    story: "He dominates all of creation. Empires, tyrants, laws of nature, and death itself are entirely submissive to His power.",
    benefits: "Invoked to break the chains of bad habits, addictions, or external oppression, seeking Allah's power to conquer obstacles."
  },
  {
    id: "name_16",
    tr: "Al-Wahhab",
    arabic: "الْوَهَّابُ",
    en: "The Supreme Bestower",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught: 'Ask Allah of His bounty, for Allah loves to be asked.'",
    story: "He gives gifts continuously without expecting anything in return. His blessings are not earned; they are pure gifts of love.",
    benefits: "Recited when seeking blessings, children, guidance, or sustenance, knowing that Allah gives freely and without limit."
  },
  {
    id: "name_17",
    tr: "Al-Razzaq",
    arabic: "الرَّزَّاقُ",
    en: "The All-Provider",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'If you were to rely upon Allah with right reliance, He would provide for you as He provides for the birds.' (Tirmidhi)",
    story: "He is the sole source of all sustenance. He provides physical food, shelter, wealth, and spiritual sustenance like knowledge and peace.",
    benefits: "Eases financial anxiety and fear of poverty, reassuring the heart that one's written sustenance will always reach them."
  },
  {
    id: "name_18",
    tr: "Al-Fattah",
    arabic: "الْفَتَّاحُ",
    en: "The Opener / Arbitrator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught that when entering a mosque, say: 'O Allah, open for me the gates of Your mercy' (Allahu-maf tah li abwaba rahmatik).",
    story: "He opens locked doors, resolves confusing situations, brings victory, and grants understanding and clarity when we are stuck.",
    benefits: "Invoked when facing a deadlock, starting a new project, or seeking clarity during confusing times of life."
  },
  {
    id: "name_19",
    tr: "Al-Alim",
    arabic: "الْعَلِيمُ",
    en: "The All-Knowing",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'I seek refuge in Allah, the All-Hearing, the All-Knowing, from the accursed Shaytan.'",
    story: "He knows everything — past, present, future, what is hidden in the depths of our hearts, and even what would have happened if things went differently.",
    benefits: "Brings peace during trials, knowing that Allah understands what we are going through, even if we cannot explain it to anyone."
  },
  {
    id: "name_20",
    tr: "Al-Qabid",
    arabic: "الْقَابِضُ",
    en: "The Constrictor / Withholder",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah is the one who constricts (Al-Qabid) and expands (Al-Basit), and He is the Provider.' (Abu Dawud)",
    story: "He constricts hearts or wealth to test our patience, draw us closer, or protect us from harm that we cannot foresee.",
    benefits: "Invoked during emotional dry spells or financial constraints, reminding us that difficulty is temporary and serves a divine purpose."
  },
  {
    id: "name_21",
    tr: "Al-Basit",
    arabic: "الْبَاسِطُ",
    en: "The Expander / Releaser",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, none can constrict what You expand, and none can expand what You constrict.'",
    story: "He expands hearts with joy and increases sustenance with abundance, bringing ease and relief after a period of constriction.",
    benefits: "Recited to seek emotional relief, joy, spiritual openness, and abundance after experiencing hardship."
  },
  {
    id: "name_22",
    tr: "Al-Khafid",
    arabic: "الْخَافِضُ",
    en: "The Abaser / Humiliator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'He lowers (Al-Khafid) and elevates (Al-Rafi').' (Muslim)",
    story: "He debases the arrogant, the tyrants, and those who associate partners with Him, showing the fragility of worldly pride.",
    benefits: "Cultivates humility and serves as a warning against arrogance, showing that true honor belongs only to Allah."
  },
  {
    id: "name_23",
    tr: "Al-Rafi'",
    arabic: "الرَّافِعُ",
    en: "The Exalter / Elevator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'No one humbles themselves before Allah except that Allah exalts them (Rafa'ahu).' (Muslim)",
    story: "He elevates the status of the humble, the scholars, the righteous, and those who perform sincere acts of worship.",
    benefits: "Encourages humility, showing that the path to true dignity and elevation lies in humbling oneself before the Divine."
  },
  {
    id: "name_24",
    tr: "Al-Mu'izz",
    arabic: "الْمُعِزُّ",
    en: "The Giver of Honor",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran says: 'You honor whom You will (Tu'izzu man tasha) and humiliate whom You will.' (Surah Ali 'Imran 3:26)",
    story: "He gives honor, power, and dignity to individuals or nations who follow truth and act with justice.",
    benefits: "Invoked when seeking dignity, strength, and respect in one's personal life or community."
  },
  {
    id: "name_25",
    tr: "Al-Mudhill",
    arabic: "الْمُذِلُّ",
    en: "The Giver of Dishonor",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ warned: 'Seek refuge in Allah from disgrace (dhillah).' (Bukhari)",
    story: "He withdraws His support and guidance from the unjust, leaving them to fall into disgrace as a consequence of their choices.",
    benefits: "Recited to seek protection from humiliation, debt, disgrace, and being overpowered by unjust forces."
  },
  {
    id: "name_26",
    tr: "Al-Sami'",
    arabic: "السَّمِيعُ",
    en: "The All-Hearing",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'O people! Be kind to yourselves, for you are not calling upon one who is deaf or absent, but upon the All-Hearing, the All-Seeing.' (Bukhari)",
    story: "He hears all sounds, silent prayers, whispers, and even the unvoiced thoughts moving in our minds.",
    benefits: "Encourages us to talk to Allah in private, knowing that every sigh and silent plea is heard perfectly."
  },
  {
    id: "name_27",
    tr: "Al-Basir",
    arabic: "الْبَصِيرُ",
    en: "The All-Seeing",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said regarding Ihsan: 'It is to worship Allah as if you see Him; and if you do not see Him, He sees you.' (Bukhari)",
    story: "Nothing escapes His sight. He sees the black ant on a dark stone in the middle of a pitch-black night.",
    benefits: "Creates mindfulness (*Muraqabah*) in secret actions and reassures us that Allah sees our good deeds, even if they are hidden from others."
  },
  {
    id: "name_28",
    tr: "Al-Hakam",
    arabic: "الْحَكَمُ",
    en: "The Ultimate Judge",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah is the Judge (Al-Hakam), and to Him belongs all judgment.' (Abu Dawud)",
    story: "He is the arbitrator whose decrees are absolutely just. No one can overturn His ruling, and He will judge between creation on the Day of Judgment.",
    benefits: "Instills comfort that ultimate justice will be served, easing the pain of worldly injustices that remain unresolved."
  },
  {
    id: "name_29",
    tr: "Al-Adl",
    arabic: "الْعَدْلُ",
    en: "The Utterly Just",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in a Hadith Qudsi: 'O My servants, I have forbidden injustice for Myself and made it forbidden among you, so do not oppress one another.' (Muslim)",
    story: "He is absolute justice. He never oppresses, does no wrong, and ensures everything in creation is placed in its perfect right place.",
    benefits: "Encourages the reciter to act justly in their own life, treating family, colleagues, and all creation with fairness."
  },
  {
    id: "name_30",
    tr: "Al-Lateef",
    arabic: "اللَّطِيفُ",
    en: "The Subtle / Gentle / Kind",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Indeed, Allah is kind (Lateef) and He loves kindness.' (Muslim)",
    story: "He acts with subtle grace. He delivers blessings and answers prayers in ways so gentle and unexpected that we barely notice them unfolding.",
    benefits: "Traditionally recited 129 times in moments of distress to ask for gentle ease, relief, and subtle solutions to difficult trials."
  },
  {
    id: "name_31",
    tr: "Al-Khabeer",
    arabic: "الْخَبِيرُ",
    en: "The All-Aware",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Should He not know what He created? And He is the Subtle, the All-Aware (Al-Khabeer).' (Surah Al-Mulk 67:14)",
    story: "He knows the inner realities, hidden motives, and structural details of all things. Nothing is concealed from His awareness.",
    benefits: "Prompts sincerity in intentions, reminding us that Allah knows the true motives behind our public actions."
  },
  {
    id: "name_32",
    tr: "Al-Haleem",
    arabic: "الْحَلِيمُ",
    en: "The Most Forbearing",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to say in distress: 'La ilaha illallahul 'Azeemul-Haleem' (There is no god but Allah, the Magnificent, the Forbearing).",
    story: "He does not rush to punish us when we make mistakes. He gives us time, space, and opportunities to turn back, repent, and correct ourselves.",
    benefits: "Fosters patience and forbearance toward others. Recited to ask for emotional control and calm during anger."
  },
  {
    id: "name_33",
    tr: "Al-Azeem",
    arabic: "الْعَظِيمُ",
    en: "The Magnificent / Infinite",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Two phrases are light on the tongue, heavy on the scale... SubhanAllahi wa bihamdihi, SubhanAllahil-Azeem.' (Bukhari)",
    story: "He is beyond human comprehension. His glory, power, and magnificence have no limits, boundaries, or end.",
    benefits: "Builds awe and reverence during prayer, helping us feel small in a comforting way before the grandeur of the Creator."
  },
  {
    id: "name_34",
    tr: "Al-Ghafoor",
    arabic: "الْغَفُورُ",
    en: "The All-Forgiving",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught Abu Bakr to pray: 'O Allah, I have wronged myself... and none can forgive sins but You, so grant me forgiveness (Maghfirah)...' (Bukhari)",
    story: "Al-Ghafoor forgives completely, wrapping our sins in His mercy so that they leave no trace, guilt, or punishment.",
    benefits: "Wipes away despair and hopelessness. Recited to seek forgiveness for major, minor, or repeated slip-ups."
  },
  {
    id: "name_35",
    tr: "Al-Shakoor",
    arabic: "الشَّكُورُ",
    en: "The Most Appreciative / Grateful",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah thanked a man (Fashakara lahu) who removed a thorny branch from the path, and forgave him.' (Bukhari)",
    story: "He multiplies the reward of small deeds. He appreciates and rewards our smallest efforts, even when we fall short in our duties.",
    benefits: "Encourages us to keep doing small acts of kindness, knowing that no good deed goes unacknowledged by Al-Shakoor."
  },
  {
    id: "name_36",
    tr: "Al-Aliyy",
    arabic: "الْعَلِيُّ",
    en: "The Most High",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran says: 'And He is the Most High, the Most Great (Al-Aliyyul-'Azeem).' (Surah Al-Baqarah 2:255)",
    story: "He is exalted above all creation in status, power, and essence. No thought or description can reach His high reality.",
    benefits: "Brings perspective. When facing a giant problem, reminding oneself of Al-Aliyy makes the problem seem tiny."
  },
  {
    id: "name_37",
    tr: "Al-Kabeer",
    arabic: "الْكَبِيرُ",
    en: "The Greatest",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'The key to Paradise is the testimony of faith... and declaring Allah's greatness (Takbeer).'",
    story: "He is larger than anything we can imagine. His grandeur, majesty, and essence are infinitely superior to all of existence.",
    benefits: "Invoked to push away anxiety, reminding ourselves that Allah is greater (*Allahu Akbar*) than any worry or threat."
  },
  {
    id: "name_38",
    tr: "Al-Hafiz",
    arabic: "الْحَفِيظُ",
    en: "The Preserver / Protector",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Be mindful of Allah, and He will protect you (Yahfazka).' (Tirmidhi)",
    story: "He protects our physical bodies from harm and preserves our spiritual faith from doubts, maintaining the universe in perfect balance.",
    benefits: "Invoked when traveling, during danger, or to seek protection for children, family, and wealth."
  },
  {
    id: "name_39",
    tr: "Al-Muqeet",
    arabic: "الْمُقِيتُ",
    en: "The Nourisher / Sustainer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'It is sufficient sin for a person to withhold food from those whom he is supposed to feed.'",
    story: "He provides the exact nourishment needed for every living creature to survive and thrive, down to the cellular level.",
    benefits: "Recited to seek physical health, energy, and spiritual strength during times of fasting or weakness."
  },
  {
    id: "name_40",
    tr: "Al-Haseeb",
    arabic: "الْحَسِيبُ",
    en: "The Sufficient Reckoner",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'And sufficient is Allah as a Reckoner (Al-Haseeb).' (Surah An-Nisa 4:6)",
    story: "He is enough for us. He keeps a perfect account of all deeds, and His protection is fully sufficient for anyone who relies on Him.",
    benefits: "Recited to build self-sufficiency, reducing dependency on people's approval or validation."
  },
  {
    id: "name_41",
    tr: "Al-Jaleel",
    arabic: "الْجَلِيلُ",
    en: "The Majestic",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to pray: 'Tabarakta ya Dhal-Jalali wal-Ikram' (Blessed are You, Possessor of Majesty and Honor).",
    story: "He is the source of all majesty, glory, and sublimity, commanding awe and respect from all of creation.",
    benefits: "Recited to invoke awe, dignity, and beauty in one's heart, character, and surroundings."
  },
  {
    id: "name_42",
    tr: "Al-Kareem",
    arabic: "الْكَرِيمُ",
    en: "The Generous / Bountiful",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Your Lord is bashful and generous (Kareem). He is shy to let His servant go empty-handed when they raise their hands to Him.' (Tirmidhi)",
    story: "He gives abundantly without being asked, forgives even when He has the power to punish, and rewards beyond what we deserve.",
    benefits: "Recited when making Dua to build trust and hope that Allah will answer in the most generous way."
  },
  {
    id: "name_43",
    tr: "Al-Raqeeb",
    arabic: "الرَّقِيبُ",
    en: "The Watchful Guardian",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Faith is to know that Allah is with you wherever you are.'",
    story: "He watches over us with loving care, observing every action, word, and heart flutter. Nothing escapes His vigilance.",
    benefits: "Brings comfort that we are never alone, and builds mindfulness to avoid secret sins."
  },
  {
    id: "name_44",
    tr: "Al-Mujeeb",
    arabic: "الْمُجِيبُ",
    en: "The Responder to Prayers",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'There is no Muslim who calls upon Allah with a supplication... except that Allah grants him one of three things...' (Ahmad)",
    story: "He answers every sincere call. His response might be immediate, delayed for a better time, or replaced with something far better.",
    benefits: "Restores hope when prayers seem unanswered, reassuring us that Al-Mujeeb is active and listening."
  },
  {
    id: "name_45",
    tr: "Al-Wasi'",
    arabic: "الْوَاسِعُ",
    en: "The All-Encompassing / Boundless",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah's hand is full, and its fullness is not diminished by continuous spending day and night.'",
    story: "His mercy, knowledge, wealth, and power are infinite. There is no limit to what He can create, give, or forgive.",
    benefits: "Eases feelings of lack, claustrophobia, or hopelessness, reminding us of Allah's limitless abundance."
  },
  {
    id: "name_46",
    tr: "Al-Hakeem",
    arabic: "الْحَكِيمُ",
    en: "The Wise One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, to You belongs all praise... You are the Ruler of rulers and the Wisest of judges.'",
    story: "Everything He plans, creates, permits, or prevents is done with perfect wisdom. Even when we cannot see the purpose, Al-Hakeem's design is flawless.",
    benefits: "Allows us to accept life's setbacks with patience (*Rida*), trusting that Allah's plan is better than ours."
  },
  {
    id: "name_47",
    tr: "Al-Wadood",
    arabic: "الْوَدُودُ",
    en: "The Loving One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'If Allah loves a person, He calls Jibril and says: I love so-and-so, so love him...' (Bukhari)",
    story: "He is the source of affection. Unlike other names for love, Al-Wadood implies active, showing love — sending blessings to make His love known.",
    benefits: "Recited when feeling lonely, unloved, or rejected, seeking the ultimate, reassuring love of the Creator."
  },
  {
    id: "name_48",
    tr: "Al-Majeed",
    arabic: "الْمَجِيدُ",
    en: "The All-Glorious",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "We say in the Tashahhud of Salah: 'In-naka Hameedun Majeed' (Indeed, You are Praiseworthy and All-Glorious).",
    story: "He is perfect in glory, honor, power, and benevolence, deserving the highest praise from all creation.",
    benefits: "Recited to elevate one's thoughts above worldly concerns and glorify the beauty of the Divine."
  },
  {
    id: "name_49",
    tr: "Al-Ba'ith",
    arabic: "الْبَاعِثُ",
    en: "The Resurrector",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught us to say when waking up: 'Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushoor' (All praise to Him who gave us life... and to Him is the resurrection).",
    story: "He will bring all dead bodies back to life on the Day of Judgment, and He revives dead, hopeless hearts in this life.",
    benefits: "Instills belief in the afterlife and accountability, and brings hope of revival to dull, spiritually dry hearts."
  },
  {
    id: "name_50",
    tr: "Al-Shahid",
    arabic: "الشَّهِيدُ",
    en: "The Witness",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'And Allah is Witness over all things (Al-Shahid).' (Surah Al-Mujadila 58:6)",
    story: "He is the ultimate witness who observes everything, both open and hidden. Nothing can be falsified or hidden from Him.",
    benefits: "Brings comfort to those who are misunderstood or falsely accused, knowing that Allah is their perfect Witness."
  },
  {
    id: "name_51",
    tr: "Al-Haqq",
    arabic: "الْحَقُّ",
    en: "The Absolute Truth",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed at night: 'Antal-Haqq, wa wa'duka-Haqq, wa qawluka-Haqq' (You are the Truth, Your promise is true, Your word is true).",
    story: "He is the only absolute reality. Everything else exists because He created it. His laws, promise, and judgment are the ultimate truth.",
    benefits: "Keeps the reciter anchored in reality, clearing away falsehoods, illusions, and doubts."
  },
  {
    id: "name_52",
    tr: "Al-Wakeel",
    arabic: "الْوَكِيلُ",
    en: "The Trustworthy Trustee",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "When threatened, the companions said: 'Hasbunallahu wa ni'mal-wakeel' (Allah is sufficient for us, and He is the best Disposer of affairs). (Bukhari)",
    story: "He is the one we delegate our affairs to. When we do our best and trust Him, Al-Wakeel manages the outcome perfectly.",
    benefits: "Relieves the burden of overthinking and control, allowing the reciter to find peace in divine custody."
  },
  {
    id: "name_53",
    tr: "Al-Qawiyy",
    arabic: "الْقَوِيُّ",
    en: "The Strong One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'A strong believer is better and more beloved to Allah than a weak believer...' (Muslim)",
    story: "His strength is infinite, independent, and never decreases. No resistance can withstand His power.",
    benefits: "Invoked when feeling physically exhausted, weak, or facing powerful, oppressive adversaries."
  },
  {
    id: "name_54",
    tr: "Al-Meteen",
    arabic: "الْمَتِينُ",
    en: "The Firm / Steadfast",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Indeed, Allah is the Provider, possessor of strength, the Firm (Al-Meteen).' (Surah Adh-Dhariyat 51:58)",
    story: "He is firm and unwavering. His power is solid, stable, and subject to no fatigue, weakness, or interruption.",
    benefits: "Recited to seek steadfastness (*Istiqamah*) in faith and principles when facing trials or peer pressure."
  },
  {
    id: "name_55",
    tr: "Al-Waliyy",
    arabic: "الْوَلِيُّ",
    en: "The Protective Friend / Patron",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says: 'Allah is the Waliyy of those who believe. He brings them out from darkness into light.' (Surah Al-Baqarah 2:257)",
    story: "He is the ally of the believers, supporting, guiding, and loving them. He takes care of their affairs like a close guardian.",
    benefits: "Invoked when feeling lonely or abandoned, seeking Allah's protective friendship and guidance."
  },
  {
    id: "name_56",
    tr: "Al-Hameed",
    arabic: "الْحَمِيدُ",
    en: "The Praiseworthy",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Alhamdulillah fills the scale (of good deeds).' (Muslim)",
    story: "He is inherently praiseworthy. Even if no one praised Him, He remains praiseworthy due to His beautiful attributes and blessings.",
    benefits: "Reciting this name builds a habit of gratitude, shifting focus from what is missing to the blessings that exist."
  },
  {
    id: "name_57",
    tr: "Al-Muhsy",
    arabic: "الْمُحْصِي",
    en: "The Counter / Appraiser",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'He has encompassed them and numbered them with an exact numbering.' (Surah Maryam 19:94)",
    story: "He counts everything. Every leaf that falls, every drop of rain, every second of time, and every deed we perform is logged.",
    benefits: "Reminds us that no effort is wasted. Every small action is counted and valued by Allah."
  },
  {
    id: "name_58",
    tr: "Al-Mubdi",
    arabic: "الْمُبْدِئُ",
    en: "The Initiator / Producer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Indeed, He originates creation (Al-Mubdi) and repeats it.' (Surah Buruj 85:13)",
    story: "He starts everything. He created the universe and life from nothing, initiating the laws of existence.",
    benefits: "Invoked when starting a new venture, business, or phase of life, asking Allah to initiate it with blessings."
  },
  {
    id: "name_59",
    tr: "Al-Mu'eed",
    arabic: "الْمُعِيدُ",
    en: "The Restorer / Reproducer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught: 'Seek cure from Allah... for He is the one who restores health.'",
    story: "He repeats creation and restores what has withered. He can restore broken health, lost wealth, and dead hearts.",
    benefits: "Recited when seeking recovery from illness, trauma, or rebuild after a massive loss."
  },
  {
    id: "name_60",
    tr: "Al-Muhyi",
    arabic: "الْمُحْيِي",
    en: "The Giver of Life",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah... You give life and cause death.'",
    story: "He breathes life into dust, created souls, and brings rain to revive dead soil. He is the owner of life.",
    benefits: "Recited to seek physical vitality, recovery from disease, and spiritual revival for a dull heart."
  },
  {
    id: "name_61",
    tr: "Al-Mumeet",
    arabic: "الْمُمِيتُ",
    en: "The Giver of Death",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'O Allah, in Your name I die and I live.' (Bukhari)",
    story: "He decrees the end of physical life for all things. Death is not a system failure; it is a transition created by Him.",
    benefits: "Reminds the reciter of their mortality, helping prioritize what truly matters and reducing attachment to the temporary world."
  },
  {
    id: "name_62",
    tr: "Al-Hayy",
    arabic: "الْحَيُّ",
    en: "The Ever-Living",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to say in distress: 'Ya Hayyu Ya Qayyum, bi-rahmatika astagheeth' (O Ever-Living, O Self-Sustaining, in Your mercy I seek relief).",
    story: "He is eternally alive. His life has no beginning and no end, and is free from sleep, fatigue, or decay.",
    benefits: "Invoking Al-Hayy connects the heart to the source of eternal existence, bringing stability and comfort during times of grief."
  },
  {
    id: "name_63",
    tr: "Al-Qayyum",
    arabic: "الْقَيُّومُ",
    en: "The Self-Sustaining",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said that Allah's greatest name (Ism Allah al-A'zam) is contained in Ayat al-Kursi, which begins with 'Al-Hayyul-Qayyum'.",
    story: "He exists independently of all creation, while all of creation depends on Him for every second of its existence.",
    benefits: "Brings security, knowing that Al-Qayyum is holding the universe and our lives together, even when we feel overwhelmed."
  },
  {
    id: "name_64",
    tr: "Al-Wajid",
    arabic: "الْوَاجِدُ",
    en: "The Finder / Perceiver",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in the Quran: 'Did He not find you (Wajadaka) an orphan and shelter you?' (Surah Ad-Duha 93:6)",
    story: "He possesses everything. Nothing is lost to Him, and He finds and knows every soul, never forgetting or overlooking anyone.",
    benefits: "Recited when feeling lost or forgotten, finding comfort that Al-Wajid knows where we are and what we need."
  },
  {
    id: "name_65",
    tr: "Al-Majid",
    arabic: "الْمَاجِدُ",
    en: "The Noble / Glorious",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Glorify your Lord, for He loves to be glorified.'",
    story: "He is full of nobility, honor, and generosity, deserving respect and love from all His servants.",
    benefits: "Recited to build noble character and seek honor through devotion to the Divine."
  },
  {
    id: "name_66",
    tr: "Al-Wahid",
    arabic: "الْوَاحِدُ",
    en: "The One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Declaring the oneness of Allah (Tawheed) is the absolute core of faith.'",
    story: "He is unique and indivisible. There is none like Him, and He has no partners, children, or equals.",
    benefits: "Recited to clarify faith and clean the mind from seeking approval from multiple worldly authorities."
  },
  {
    id: "name_67",
    tr: "Al-Ahad",
    arabic: "الْأَحَدُ",
    en: "The Unique / Indivisible",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Surah Al-Ikhlas (which mentions Al-Ahad) is equal to one-third of the Quran.' (Bukhari)",
    story: "He is singularly unique in His essence and attributes. He is completely independent and has no match.",
    benefits: "Strengthens conviction and frees the heart from fear of creation, focusing entirely on the One."
  },
  {
    id: "name_68",
    tr: "Al-Samad",
    arabic: "الصَّمَدُ",
    en: "The Eternal Refuge / Besought of All",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ explained: 'Al-Samad is the master whose control is absolute, and upon whom all creation depends.'",
    story: "He is hollowless and solid, needing nothing (food, rest, support), while everyone and everything needs Him for their needs.",
    benefits: "The ultimate name to invoke when in absolute need, turning to Al-Samad as the eternal refuge."
  },
  {
    id: "name_69",
    tr: "Al-Qadir",
    arabic: "الْقَادِرُ",
    en: "The Capable / All-Powerful",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, I seek Your guidance through Your knowledge, and I seek power through Your power (Qudrah)...'",
    story: "He has the power to do whatever He wills. No plan of His can be blocked, and He is capable of changing any situation in an instant.",
    benefits: "Invoked when facing impossible odds, seeking Allah's capability to make the impossible happen."
  },
  {
    id: "name_70",
    tr: "Al-Muqtadir",
    arabic: "الْمُقْتَدِرُ",
    en: "The Determiner / Dominant Creator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'In a seat of truth near a Sovereign Perfect in Ability (Muqtadir).' (Surah Al-Qamar 54:55)",
    story: "His power is active and absolute, shaping destiny and executing events according to His wisdom.",
    benefits: "Recited to find courage, knowing that the ultimate controller of all circumstances is Al-Muqtadir."
  },
  {
    id: "name_71",
    tr: "Al-Muqaddim",
    arabic: "الْمُقَدِّمُ",
    en: "The Expediter / Promoter",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed at night: 'Antal-Muqaddim wa Antal-Mu'akhkhir' (You are the one who brings forward and You are the one who puts back). (Bukhari)",
    story: "He decides what happens first, promoting whoever He wills in status, honor, and time.",
    benefits: "Recited to ask for progress, speed, and success in good deeds, and promotion in spiritual ranks."
  },
  {
    id: "name_72",
    tr: "Al-Mu'akhkhir",
    arabic: "الْمُؤَخِّرُ",
    en: "The Delayer / Postponer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'Forgive me what I have sent forward and what I have delayed (Akhkhartu)...'",
    story: "He delays events or status for a wise reason. If He holds something back from us, it is out of mercy or protection.",
    benefits: "Helps accept delays and blockages in life with patience, trusting that Allah's timing is perfect."
  },
  {
    id: "name_73",
    tr: "Al-Awwal",
    arabic: "الْأَوَّلُ",
    en: "The First",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, You are the First (Al-Awwal), and there is nothing before You.' (Muslim)",
    story: "He existed before anything else was created. He has no beginning, and He is the source of all existence.",
    benefits: "Keeps our priorities straight, reminding us to put Allah first in all actions and decisions."
  },
  {
    id: "name_74",
    tr: "Al-Akhir",
    arabic: "الْآخِرُ",
    en: "The Last",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, You are the Last (Al-Akhir), and there is nothing after You.'",
    story: "He will remain when everything else in the universe ceases to exist. He is the ultimate destination of all souls.",
    benefits: "Helps us focus on our legacy and the afterlife, knowing that only our deeds and relationship with Al-Akhir endure."
  },
  {
    id: "name_75",
    tr: "Al-Zahir",
    arabic: "الظَّاهِرُ",
    en: "The Manifest / Evident",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, You are the Manifest (Al-Zahir), and there is nothing above You.'",
    story: "His existence is clearly manifest through His signs, the order of nature, and the miracle of life.",
    benefits: "Enriches reflection on nature and the cosmos, finding evidence of the Creator in all of creation."
  },
  {
    id: "name_76",
    tr: "Al-Batin",
    arabic: "الْبَاطِنُ",
    en: "The Hidden / Imperceptible",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, You are the Hidden (Al-Batin), and there is nothing beneath You.'",
    story: "He cannot be seen by human eyes in this world, yet He is closer to us than our jugular vein, aware of our innermost secrets.",
    benefits: "Brings comfort that Allah is intimately close to us, understanding our silent feelings and hidden tears."
  },
  {
    id: "name_77",
    tr: "Al-Wali",
    arabic: "الْوَالِي",
    en: "The Governor / Sole Director",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'And they have no protector (Wali) other than Him.' (Surah Ar-Ra'd 13:11)",
    story: "He is the sole planner and administrator of the entire universe, directing all events according to His wisdom.",
    benefits: "Recited to find peace, knowing that Al-Wali is managing the cosmos and our lives with absolute capability."
  },
  {
    id: "name_78",
    tr: "Al-Muta'ali",
    arabic: "الْمُتَعَالِي",
    en: "The Supreme Exalted",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ declared: 'Glorified and exalted (Ta'ala) is He above what they associate with Him.'",
    story: "He is exalted above any description, human limitation, or comparison, possessing supreme grandeur.",
    benefits: "Recited to raise one's perspective and build deep reverence during acts of worship."
  },
  {
    id: "name_79",
    tr: "Al-Barr",
    arabic: "الْبَرُّ",
    en: "The Source of All Goodness / Kind",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Indeed, it is He who is the Beneficent (Al-Barr), the Merciful.' (Surah At-Tur 52:28)",
    story: "He is the source of all kindness, charity, and good. He loves ease for His servants and continuously showers them with goodness.",
    benefits: "Fosters a positive attitude and kindness toward others, reflecting Al-Barr's goodness in one's character."
  },
  {
    id: "name_80",
    tr: "Al-Tawwab",
    arabic: "التَّوَّابُ",
    en: "The Accepter of Repentance",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Allah is more pleased with the repentance of His servant than one of you who finds his lost camel in the desert.' (Bukhari)",
    story: "He continually turns back to His servants, inspiring them to repent and accepting their apologies, no matter how many times they slip up.",
    benefits: "The go-to name for those seeking repentance, clearing away the whispers of Shaytan that we are too far gone."
  },
  {
    id: "name_81",
    tr: "Al-Muntaqim",
    arabic: "الْمُنْتَقِمُ",
    en: "The Avenger",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Indeed, We, from the criminals, will take retribution (Muntaqimoon).' (Surah As-Sajdah 32:22)",
    story: "He is the punisher of severe oppressors and tyrants who refuse to stop causing corruption and hurting the innocent.",
    benefits: "Brings comfort to victims of oppression, knowing that Al-Muntaqim will hold oppressors accountable."
  },
  {
    id: "name_82",
    tr: "Al-Afuww",
    arabic: "العَفُوُّ",
    en: "The Supreme Pardoner",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ taught Aisha to pray on Laylat al-Qadr: 'Allahumma innaka 'Afuwwun tuhibbul-'afwa fa'fu 'anni' (O Allah, You are the Pardoner, You love to pardon, so pardon me). (Tirmidhi)",
    story: "Al-Afuww does not just forgive; He pardons, erasing the sin from our records entirely as if it never happened.",
    benefits: "Recited to seek complete removal of sins and relief from guilt, particularly during Ramadan and sacred nights."
  },
  {
    id: "name_83",
    tr: "Al-Ra'oof",
    arabic: "الرَّؤُوفُ",
    en: "The Compassionate / Kind",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'And indeed, Allah to you is Kind (Ra'oof) and Merciful.' (Surah Al-Hadid 57:9)",
    story: "He is filled with tender compassion. His mercy is so gentle that He shields us from burdens we cannot bear.",
    benefits: "Recited to ask for gentleness in life's circumstances and compassion in one's relations."
  },
  {
    id: "name_84",
    tr: "Malik-ul-Mulk",
    arabic: "مَالِكُ الْمُلْكِ",
    en: "The Owner of All Sovereignty",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'O Owner of Majesty and Honor, keep us firm on Your path.'",
    story: "He is the absolute owner of all kingdoms, wealth, power, and domains, ruling without any advisor or co-owner.",
    benefits: "Recited to find humility and seek stability, knowing that all worldly power and wealth are temporary loans from Him."
  },
  {
    id: "name_85",
    tr: "Dhul-Jalali wal-Ikram",
    arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ",
    en: "The Owner of Majesty and Honor",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Adhere constantly to Dhul-Jalali wal-Ikram (in your prayers).' (Tirmidhi)",
    story: "He is the possessor of supreme glory, greatness, and majesty, yet He is also the source of honor and generosity toward His servants.",
    benefits: "Highly recommended by the Prophet ﷺ to repeat during supplications to ensure they are answered."
  },
  {
    id: "name_86",
    tr: "Al-Muqsit",
    arabic: "الْمُقْسِطُ",
    en: "The Equitable / Just",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Indeed, the equitable (Al-Muqsitoon) will be on pulpits of light on the Day of Resurrection.' (Muslim)",
    story: "He acts with perfect equity, resolving conflicts, balancing scales, and ensuring everyone receives their exact rights.",
    benefits: "Invoked to resolve disputes, cultivate fairness, and ask for peace in conflicted families or communities."
  },
  {
    id: "name_87",
    tr: "Al-Jami'",
    arabic: "الْجَامِعُ",
    en: "The Gatherer / Uniter",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'Our Lord, surely You will gather (Jami') mankind for a Day about which there is no doubt.' (Surah Ali 'Imran 3:9)",
    story: "He gathers all of mankind on the Day of Judgment, and He unites scattered hearts, divided families, and lost items.",
    benefits: "Invoked to seek unity in families, locate missing items, or bring scattered communities together."
  },
  {
    id: "name_88",
    tr: "Al-Ghaniyy",
    arabic: "الْغَنِيُّ",
    en: "The Self-Sufficient / Rich",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in a Hadith Qudsi: 'O My servants, if the first of you and the last of you... were to ask Me and I gave everyone what they asked, that would not decrease what I have...' (Muslim)",
    story: "He is completely rich and self-sufficient. He needs no worship or creation, while all creation is in absolute need of Him.",
    benefits: "Recited to ask for financial independence (*Ghena*) and free the heart from greed and worry."
  },
  {
    id: "name_89",
    tr: "Al-Mughni",
    arabic: "الْمُغْنِي",
    en: "The Enricher",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed: 'O Allah, make me content with what You have provided me, and bless it for me.'",
    story: "He enriches His servants, giving them wealth, content hearts, and resources to live comfortably and satisfy their needs.",
    benefits: "Invoked when seeking financial expansion and contentment (*Rida*) with one's provision."
  },
  {
    id: "name_90",
    tr: "Al-Mani'",
    arabic: "الْمَانِعُ",
    en: "The Withholder / Preventer",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ used to say: 'O Allah, none can prevent (Mani') what You give, and none can give what You prevent.' (Bukhari)",
    story: "He blocks harm from reaching us, and withholds certain blessings when they would lead to our spiritual ruin.",
    benefits: "Helps us accept when doors close, trusting that Al-Mani' blocked it out of protection, not deprivation."
  },
  {
    id: "name_91",
    tr: "Al-Darr",
    arabic: "الضَّارُّ",
    en: "The Giver of Adversity",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Know that if the whole nation gathered to harm you, they could not harm you except with what Allah wrote.'",
    story: "He permits adversity and trials to test our faith, cleanse our sins, and build our spiritual character.",
    benefits: "Eases fear of bad luck or external harm, reminding us that all trials are under divine control."
  },
  {
    id: "name_92",
    tr: "Al-Nafi'",
    arabic: "النَّافِعُ",
    en: "The Giver of Benefit",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'The most beloved of people to Allah are those who bring the most benefit to others.'",
    story: "He is the source of all benefit and good. No medicine can heal and no resource can help unless Al-Nafi' permits it.",
    benefits: "Invoked when seeking healing, success, and asking Allah to make us a source of benefit to others."
  },
  {
    id: "name_93",
    tr: "Al-Noor",
    arabic: "النُّورُ",
    en: "The Light",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ prayed at night: 'O Allah, to You belongs praise. You are the light of the heavens and the earth.' (Bukhari)",
    story: "He is the source of all physical light in the cosmos, and the spiritual light of guidance, clarity, and truth in our hearts.",
    benefits: "Recited to seek guidance, clarity, and light in the heart when passing through dark, depressing times."
  },
  {
    id: "name_94",
    tr: "Al-Hadi",
    arabic: "الْهَادِي",
    en: "The Guide",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "Allah says in a Hadith Qudsi: 'O My servants, all of you are astray except those whom I have guided, so seek guidance from Me.' (Muslim)",
    story: "He guides the birds to their nests, the baby to nurse, and the seeking heart to the path of truth, faith, and clarity.",
    benefits: "The perfect name to invoke when lost, confused, or facing a major decision, asking Al-Hadi for direction."
  },
  {
    id: "name_95",
    tr: "Al-Badi'",
    arabic: "الْبَدِيعُ",
    en: "The Incomparable Originator",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'The Originator of the heavens and the earth (Badi').' (Surah Al-Baqarah 2:117)",
    story: "He created the universe with absolute originality, without any model, predecessor, or blueprint.",
    benefits: "Recited to find inspiration, creativity, and solutions to problems that have no obvious precedent."
  },
  {
    id: "name_96",
    tr: "Al-Baqi",
    arabic: "الْبَاقِي",
    en: "The Everlasting",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Quran states: 'And there will remain the Face of your Lord, Owner of Majesty and Honor.' (Surah Ar-Rahman 55:27)",
    story: "He remains forever. Time does not apply to Him. When the universe collapses, Al-Baqi will endure eternally.",
    benefits: "Recited to find stability when facing loss, death, or change, grounding ourselves in the Everlasting."
  },
  {
    id: "name_97",
    tr: "Al-Warith",
    arabic: "الْوَارِثُ",
    en: "The Inheritor of All",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet Zakariya AS prayed: 'My Lord, do not leave me alone [without heir], and You are the best of inheritors (Al-Warithoon).' (Surah Al-Anbiya 21:89)",
    story: "When all owners of property and kingdoms die and leave their possessions, everything returns to its true owner: Al-Warith.",
    benefits: "Invoking this name builds detachment from wealth and ownership, easing the fear of loss."
  },
  {
    id: "name_98",
    tr: "Al-Rasheed",
    arabic: "الرَّشِيدُ",
    en: "The Righteous Guide / Teacher",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'Adhere to truthfulness, for truthfulness leads to righteousness (Rushd).'",
    story: "He leads creation to their goals with wisdom and righteousness, never making any error in His guidance.",
    benefits: "Recited when making decisions or plans, seeking the right path and execution without error."
  },
  {
    id: "name_99",
    tr: "Al-Saboor",
    arabic: "الصَّبُورُ",
    en: "The Patient One",
    target: 100,
    tags: ["names-of-allah"],
    hadith: "The Prophet ﷺ said: 'None is more patient (Saboor) in hearing offensive words than Allah. They associate partners with Him, yet He gives them health and provision.' (Bukhari)",
    story: "He is patient. He does not rush to punish the wrongdoers, allowing them time to realize their errors and repent.",
    benefits: "Recited to cultivate patience (*Sabr*) and emotional self-control when dealing with trials or difficult people."
  }
];
